<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Moofile.Example</RootNamespace>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <OutputType>Exe</OutputType>
    <AssemblyName>Moofile.Example</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Moofile/Moofile.csproj" />
  </ItemGroup>
</Project>
